name: build-on-push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
      with:
        submodules: true
    - name: rustup toolchain install
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: Rust cache
      uses: Swatinem/rust-cache@v2.2.1
    - name: Clippy checks
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build debug
      run: cargo build
    - name: Build release
      run: cargo build --release
    - name: Get built artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: unitas_setup_tool-${{ matrix.os }}
        path: |
          target/debug/unitas_setup_tool*
          target/release/unitas_setup_tool*